name = 'Atelierseaside-dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '131513'
black = '131513'
black-hg = '687d68'
blue = '3d62f5'
blue-hg = '3d62f5'
cursor = '8ca68c'
cyan = '1999b3'
cyan-hg = '1999b3'
foreground = '8ca68c'
green = '29a329'
green-hg = '29a329'
magenta = 'ad2bee'
magenta-hg = 'ad2bee'
red = 'e6193c'
red-hg = 'e6193c'
selection-background = '8ca68c'
selection-foreground = '131513'
white = '8ca68c'
white-hg = 'f0fff0'
yellow = 'c3c322'
yellow-hg = 'c3c322'
