name = 'Tokyo-Night'

[extras]
intellij-idea = ['']
vscode = ['Tokyo Night']
wallpaper = ['~/.config/gtheme/wallpapers/Tokyo-Night/chicago.jpg']

[colors]
background = '1a1b26'
black = '15161E'
black-hg = '414868'
blue = '7aa2f7'
blue-hg = '7aa2f7'
cursor = 'c0caf5'
cyan = '7dcfff'
cyan-hg = '7dcfff'
foreground = 'c0caf5'
green = '9ece6a'
green-hg = '9ece6a'
magenta = 'bb9af7'
magenta-hg = 'bb9af7'
red = 'f7768e'
red-hg = 'f7768e'
selection-background = 'c0caf5'
selection-foreground = '1a1b26'
white = 'a9b1d6'
white-hg = 'c0caf5'
yellow = 'e0af68'
yellow-hg = 'e0af68'
